FROM node:19.7-alpine
RUN mkdir /app
WORKDIR /app
COPY package.json /app/
RUN npm install
COPY ./public /app/public
COPY ./src /app/src
EXPOSE 3000
CMD node src/server.js




Other Reference Links
---------------------
Practice Test - SC-200 Exam	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-21_SC-200_Practice_papers

Interview Questions	https://github.com/kbindesh/ms-sentinel-bootcamp/blob/main/Module-20_Interview_Preparation/interview_questions.md

Commonly used Sentinel Tables	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-XX_Assignments/00_Sentinel_Tables

UEBA in Microsoft Sentinel	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-XX_Assignments/12_UEBA_for_Threat_Intelligence

Sentinel with ChatGPT	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-XX_Assignments/16_ChatGPT_Integration

Microsoft Defender XDR	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-15_Microsoft_Defender_XDR

Sentinel Cost Optimization	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-14_Cost_Optimization

MITRE ATT&CK Framework	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-11_MITRE%20ATT%26CK

Microsoft Sentinel Workbooks	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-10_Workbooks

Automate threat response	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-09_Threat_Response

Threat Hunting	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-08_Threat_Hunting

Managing Sentinel resources with ARM Templates	https://github.com/kbindesh/ms-sentinel-bootcamp/tree/main/Module-XX_Assignments/13_Sentinel_with_ARM_Templates


